### PR TITLE
Fixing some SHA256sum + fix dosbox-sdl2 build

### PR DESCRIPTION
**Pull request by magicseb**

### CODE REVIEW

**Comment by 5schatten** [comment]
I tried several of your SHA256 but still mine are fine. https://hastebin.com/vifalacepe.cs

**Comment by magicseb** [comment]
hi

i have checked on my side, my windows 10 get the same hashes as yours
my ubuntu 16.04 get different hashes on the same source ! And completly different archive with the same content... very strange.

I close this pull request, it is useless.

**Comment by magicseb** [comment]
buggy ubuntu, my bad.

**Comment by 5schatten** [comment]
@magicseb 
I appreciate PRs if you have some improvements but IMHO it's better if you check out the [support thread](https://forum.libreelec.tv/thread/12662-libreelec-9-0-reborn-remix-emulationstation-retroarch-dolphinqt-moonlight-chrome) first to talk about the stuff you've stumbled upon. What about the deps you've added? Are they missing for you? I haven't build every package from scratch or checked if some deps are missing if you *only* build this single package but if you create an image nothing should be missing since it's referenced before by other packages.

**Pull request closed without merging**
